Repository dailyge/dailyge-server, pull requests merged in 2024-09, with the labels that each got.

#140 [DLG-252] 쿠폰 발급 요청 묶음을 처리하는 API를 개발한다.
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponEventReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponEventWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventBulks.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventMemoryQueue.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventWriteDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponInMemoryRepository.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponBackgroundApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/CouponBulkProcessDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/CouponCreateDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponBulksIntegrationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventParticipantIntegrationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponBackgroundApiUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponCacheReadDaoUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponEventParticipantInMemoryQueueUnitTest.java
  storage/memory/src/main/java/project/dailyge/core/cache/coupon/CouponCacheWriteRepository.java
  storage/memory/src/main/java/project/dailyge/core/cache/coupon/CouponCacheWriteUseCase.java
Labels: feat

#142 [DLG-270] README.md 를 수정한다.
  README.md
Labels: docs

#145 [DLG-277] 클라이언트 작업 생산성을 위해 환경 변수에 따라 로직을 분기처리한다.
  dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeToken.java
  dailyge-api/src/main/java/project/dailyge/app/common/utils/CookieUtils.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponCreateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/external/oauth/GoogleOAuthManager.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/external/response/GoogleAuthorizationResponse.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/LoginApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/CookieUtilsUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeTokenUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponCreateApiUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/unittest/GoogleOAuthManagerUnitTest.java
Labels: test, refactor

#143 [DLG-269] 공지사항 등록 API를 개발한다.
  admin-api/src/main/java/project/dailyge/app/common/auth/TokenProvider.java
  admin-api/src/main/java/project/dailyge/app/common/configuration/web/AuthArgumentResolver.java
  admin-api/src/main/java/project/dailyge/app/common/exception/CommonException.java
  admin-api/src/main/java/project/dailyge/app/common/exception/ExternalServerException.java
  admin-api/src/main/java/project/dailyge/app/common/exception/UnAuthorizedException.java
  admin-api/src/main/java/project/dailyge/app/notice/application/NoticeWriteUseCase.java
  admin-api/src/main/java/project/dailyge/app/notice/application/command/NoticeCreateCommand.java
  admin-api/src/main/java/project/dailyge/app/notice/application/service/NoticeWriteService.java
  admin-api/src/main/java/project/dailyge/app/notice/exception/NoticeCodeAndMessage.java
  admin-api/src/main/java/project/dailyge/app/notice/exception/NoticeTypeException.java
  admin-api/src/main/java/project/dailyge/app/notice/persistence/NoticeWriteDao.java
  admin-api/src/main/java/project/dailyge/app/notice/presentation/NoticeCreateApi.java
  admin-api/src/main/java/project/dailyge/app/notice/presentation/request/NoticeCreateRequest.java
  admin-api/src/main/java/project/dailyge/app/notice/presentation/response/NoticeCreateResponse.java
  admin-api/src/main/java/project/dailyge/app/user/persistence/UserBlacklistWriteDao.java
  admin-api/src/main/java/project/dailyge/app/user/persistence/UserCacheReadDao.java
  admin-api/src/main/java/project/dailyge/app/user/persistence/UserCacheWriteDao.java
  admin-api/src/main/java/project/dailyge/app/user/presentation/UserBlacklistCreateApi.java
  admin-api/src/main/resources/db/rdb/changelog/release-1.0.0/schema.sql
  admin-api/src/test/java/project/dailyge/app/test/common/AuthArgumentResolverTest.java
  admin-api/src/test/java/project/dailyge/app/test/common/TokenProviderUnitTest.java
  admin-api/src/test/java/project/dailyge/app/test/notice/documentationtest/NoticeCreateDocumentation.java
  admin-api/src/test/java/project/dailyge/app/test/notice/documentationtest/snippet/NoticeCreateSnippet.java
  admin-api/src/test/java/project/dailyge/app/test/notice/documentationtest/snippet/NoticeSnippet.java
  admin-api/src/test/java/project/dailyge/app/test/user/documentationtest/UserBlacklistCreateDocumentation.java
  admin-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserBlacklistSnippet.java
  admin-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java
  admin-api/src/test/java/project/dailyge/app/test/user/unittest/UserCacheReadDaoUnitTest.java
  storage/rdb/src/main/java/project/dailyge/entity/notice/NoticeEntityWriteRepository.java
  storage/rdb/src/main/java/project/dailyge/entity/notice/NoticeJpaEntity.java
  storage/rdb/src/main/java/project/dailyge/entity/notice/NoticeType.java
  storage/rdb/src/test/java/project/dailyge/entity/test/notice/NoticeJpaEntityUnitTest.java
  storage/rdb/src/testFixtures/java/project/dailyge/entity/notice/NoticeFixture.java
Labels: feat, chore, test, refactor

#146 [DLG-279] 자신의 게시물이 아니라면 조회할 수 없도록 한다.
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/application/service/MonthlyGoalReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/persistence/MonthlyGoalReadDao.java
Labels: fix

#147 [DLG-278] JWT 내부에 email 정보를 제거한다.
  admin-api/src/main/java/project/dailyge/app/common/auth/TokenProvider.java
  admin-api/src/test/java/project/dailyge/app/test/common/AuthArgumentResolverTest.java
  admin-api/src/test/java/project/dailyge/app/test/common/TokenProviderUnitTest.java
  admin-api/src/test/java/project/dailyge/app/test/notice/documentationtest/NoticeCreateDocumentation.java
  admin-api/src/test/java/project/dailyge/app/test/user/documentationtest/UserBlacklistCreateDocumentation.java
  dailyge-api/src/main/java/project/dailyge/app/common/auth/TokenProvider.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/LoginInterceptor.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/AuthArgumentResolverTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/LoginInterceptorUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/TokenProviderUnitTest.java
Labels: test, refactor

#148 [DLG-282] CloudWatch로 로그를 전송한다.
  .gitignore
  dailyge-api/build.gradle
  dailyge-api/src/main/java/project/dailyge/app/CommonApi.java
  dailyge-api/src/main/java/project/dailyge/app/common/auth/DailygeUser.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/CloudWatchLogAppender.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/WebConfiguration.java
  dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcTaskDecorator.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/package-info.java
  dailyge-api/src/main/java/project/dailyge/app/common/utils/IpUtils.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeUserUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/MdcTaskDecoratorUnitTest.java
  support/build.gradle
  support/src/main/java/project/dailyge/app/constant/LogConstant.java
  support/src/main/java/project/dailyge/app/utils/LogUtils.java
  support/src/test/java/project/dailyge/support/test/log/LogUtilsUnitTest.java
Labels: feat, chore, test, refactor

#150 [DLG-289] 로그 포맷 및 데이터 초기화 설정을 리팩토링한다.
  admin-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/CommonApi.java
  dailyge-api/src/main/java/project/dailyge/app/common/annotation/ApplicationLayer.java
  dailyge-api/src/main/java/project/dailyge/app/common/annotation/EventLayer.java
  dailyge-api/src/main/java/project/dailyge/app/common/annotation/ExternalLayer.java
  dailyge-api/src/main/java/project/dailyge/app/common/annotation/FacadeLayer.java
  dailyge-api/src/main/java/project/dailyge/app/common/annotation/PresentationLayer.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/aws/cloudwatch/LoggingConfig.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/AuthArgumentResolver.java
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataInitializer.java
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataWriteDao.java
  dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcTaskDecorator.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/UserBlacklistReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponEventReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponEventWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/service/CouponWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponBackgroundApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponCreateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponReadApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/application/service/MonthlyGoalReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/application/service/MonthlyGoalWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/persistence/MonthlyGoalReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/presentation/MonthlyGoalCreateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/presentation/MonthlyGoalDeleteApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/presentation/MonthlyGoalReadApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/monthlygoal/presentation/MonthlyGoalUpdateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/application/service/TaskReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/application/service/TaskWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/event/TaskEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/event/TaskEventPublisher.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/facade/TaskFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskCreateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskDeleteApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskReadApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskStatisticApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/TaskUpdateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/task/presentation/response/WeeklyTasksStatisticResponse.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/service/UserCacheReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/service/UserCacheWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/service/UserReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/service/UserWriteService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/external/oauth/GoogleOAuthManager.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/external/oauth/TokenManager.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/LoginApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserDeleteApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserReadApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/MdcTaskDecoratorUnitTest.java
  support/src/main/java/project/dailyge/app/constant/LogConstant.java
  support/src/main/java/project/dailyge/app/utils/LogUtils.java
  support/src/test/java/project/dailyge/support/test/log/LogUtilsUnitTest.java
Labels: refactor

#153 [DLG-294] 개발 서버 basicAuth 설정을 제거한다.
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
Labels: refactor

#151 [DLG-287] User 로그인 시 Logged-In 쿠키를 체크한다.
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/Cookies.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/LoginInterceptor.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/CookiesUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/LoginInterceptorUnitTest.java
Labels: chore

#156 [DLG-304] LuaScript를 사용해 사용자 캐시 조회 시, 레디스 호출 횟수를 감소시킨다.
  README.md
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScript.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScriptConfig.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/WebConfiguration.java
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataInitializer.java
  dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/BlacklistInterceptor.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/UserBlacklistReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/UserBlacklistReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/persistence/UserCacheReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/persistence/UserCacheWriteDao.java
  dailyge-api/src/test/java/project/dailyge/app/common/DatabaseInitializer.java
  dailyge-api/src/test/java/project/dailyge/app/common/DatabaseTestBase.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/BlacklistInterceptorUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/integrationtest/UserCacheReadIntegrationTest.java
Labels: docs, test, refactor

#159 [DLG-306] LuaScript를 Redis에 등록하고 EVALSHA로 실행한다.
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScript.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScriptConfig.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/persistence/UserCacheReadDao.java
  dailyge-api/src/test/java/project/dailyge/app/common/DatabaseTestBase.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/integrationtest/UserCacheReadIntegrationTest.java
  storage/memory/src/main/java/project/dailyge/common/exception/RedisExceptionUtils.java
  storage/memory/src/test/java/project/dailyge/test/common/RedisExceptionUtilsUnitTest.java
Labels: test, refactor, style

#158 [DLG-288] User Cache 정보 수정 API를 개발한다.
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/command/UserUpdateCommand.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserUpdateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/request/UserUpdateRequest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/UserUpdateDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserUpdateSnippet.java
Labels: test, refactor

#161 [DLG-307] 체크 스타일 수정사항을 반영한다.
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java
Labels: style

#162 [DLG-308] v1.0.3을 상용 서버에 배포한다.
  README.md
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScript.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/script/LuaScriptConfig.java
  dailyge-api/src/main/java/project/dailyge/app/common/configuration/web/WebConfiguration.java
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataInitializer.java
  dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/BlacklistInterceptor.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/UserBlacklistReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/UserBlacklistReadService.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/application/command/UserUpdateCommand.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/persistence/UserCacheReadDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/persistence/UserCacheWriteDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/UserUpdateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/request/UserUpdateRequest.java
  dailyge-api/src/test/java/project/dailyge/app/common/DatabaseInitializer.java
  dailyge-api/src/test/java/project/dailyge/app/common/DatabaseTestBase.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/BlacklistInterceptorUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/UserUpdateDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserSnippet.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/documentationtest/snippet/UserUpdateSnippet.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/integrationtest/UserCacheReadIntegrationTest.java
  storage/memory/src/main/java/project/dailyge/common/exception/RedisExceptionUtils.java
  storage/memory/src/test/java/project/dailyge/test/common/RedisExceptionUtilsUnitTest.java
Labels: chore

#163 [DLG-309] 재 로그인 시 User Cache가 없을 경우 새로 저장하도록 수정한다.
  dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/LoginApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/integrationtest/LoginIntegrationTest.java
Labels: refactor

#164 [DLG-310] v1.0.4을 상용 서버에 배포한다.
  dailyge-api/src/main/java/project/dailyge/app/core/user/event/UserEventListener.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
  dailyge-api/src/main/java/project/dailyge/app/core/user/presentation/LoginApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/user/integrationtest/LoginIntegrationTest.java
Labels: chore

#166 [DLG-312] v1.0.5을 상용 서버에 배포한다.
  dailyge-api/src/main/java/project/dailyge/app/core/user/facade/UserFacade.java
Labels: chore

#167 [DLG-314] 이벤트 참여 부하 테스트를 위한 설정을 추가한다.
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataInitializer.java
  jib/dailyge-api/jib.gradle
Labels: chore, refactor

#173 [DLG-317] 불필요한 Import를 제거한다.
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  storage/rdb/src/main/java/project/dailyge/entity/event/EventJpaEntity.java
Labels: chore, style

#170 [DLG-315] 쿠폰 이벤트 참여 묶음 처리하는 백그라운드 작업을 스케줄러로 처리한다.
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponBackgroundApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponSchedulerApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/request/ScheduleRateRequest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/CouponBulkProcessDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/CouponBulkSchedulerDocumentationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponBulkSchedulerTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/unittest/CouponBackgroundApiUnitTest.java
Labels: feat

#175 [DLG-318] 테스트 클래스를 default로 변경한다.
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/configuration/BlockingQueueConfig.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/persistence/CouponEventBulks.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponCreateApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/CouponSchedulerApi.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/request/ScheduleRateRequest.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/response/CouponParticipationResponse.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/presentation/validator/CouponClientValidator.java
  dailyge-api/src/main/java/project/dailyge/app/core/event/presentation/EventCreateApi.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/documentationtest/snippet/CouponCreateSnippet.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponBulkSchedulerTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/event/unittest/EventValidatorUnitTest.java
Labels: refactor

#178 [DLG-323] LogDocument _id를 별도로 생성한다.
  .github/workflows/admin-api-static-analysis.yaml
  .github/workflows/dailyge-api-ci.yaml
  config/lint/dailyge-rule.xml
  dailyge-api/src/main/java/project/dailyge/app/common/exception/GlobalExceptionHandler.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/DailygeLogAppender.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  storage/document/src/main/java/project/dailyge/document/common/UuidGenerator.java
  storage/document/src/main/java/project/dailyge/document/log/OperationLogDocument.java
  storage/document/src/test/java/project/dailyge/document/log/OperationLogDocumentUnitTest.java
  support/src/main/java/project/dailyge/app/constant/LogConstant.java
Labels: refactor

#182 [DLG-325] GCM 암호화 알고리즘을 사용하여 성능을 개선한다.
  admin-api/src/main/java/project/dailyge/app/common/auth/TokenProvider.java
  admin-api/src/test/java/project/dailyge/app/test/common/TokenProviderUnitTest.java
  dailyge-api/src/main/java/project/dailyge/app/common/auth/TokenProvider.java
  dailyge-api/src/main/resources/db/rdb/changelog/release-1.0.0/schema.sql
  dailyge-api/src/test/java/project/dailyge/app/test/common/TokenProviderUnitTest.java
Labels: chore, test, refactor

#184 [DLG-329] 부하테스트를 위해 secure 및 http only false 로 설정한다.
  dailyge-api/src/main/java/project/dailyge/app/common/utils/CookieUtils.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/CookieUtilsUnitTest.java
  dailyge-api/src/test/java/project/dailyge/app/test/common/DailygeTokenUnitTest.java
Labels: fix, test

#185 [DLG-331] 이벤트 참여 부하 테스트를 위한 설정을 추가한다.
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataInitializer.java
  dailyge-api/src/main/java/project/dailyge/app/common/data/OperationDataWriteDao.java
  dailyge-api/src/main/java/project/dailyge/app/core/common/web/ServerWarmUpRunner.java
  dailyge-api/src/main/java/project/dailyge/app/core/coupon/application/scheduler/CouponBulkScheduler.java
  jib/dailyge-api/jib.gradle
Labels: chore, refactor

#186 [DLG-332] 부하테스트를 위해 로그를 비활성화한다.
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java
Labels: fix, test

#188 [REVERT-188] 부하테스트를 위해 로그를 비활성화한다.
  dailyge-api/src/main/java/project/dailyge/app/common/log/LoggingAspect.java
  dailyge-api/src/main/java/project/dailyge/app/common/log/MdcFilter.java
  dailyge-api/src/test/java/project/dailyge/app/test/coupon/integrationtest/CouponEventValidationIntegrationTest.java
Labels: fix
